"use strict";
$import.map(
	"joopl.collections.IndexedList.test",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableList.js",
  "scripts/joopl-toolbox/collections/IndexedList.js",
  "scripts/joopl-toolbox/collections/Index.js",
  "scripts/joopl-toolbox/collections/OrderedStringIndex.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/Queryable.js"
]);
"use strict";
$import.map(
	"joopl.collections.List.test",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queue.js"
]);
"use strict";
$import.map(
	"joopl.collections.ObservableList.test",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableList.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queue.js"
]);
"use strict";
$import.map(
	"joopl.collections.Queue.test",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js"
]);
"use strict";
$import.map(
	"A",
	[
  "scripts/joopl-toolbox/A.js"
]);
"use strict";
$import.map(
	"B",
	[
  "scripts/joopl-toolbox/A.js",
  "scripts/joopl-toolbox/B.js"
]);
"use strict";
$import.map(
	"Convert",
	[
  "scripts/joopl-toolbox/Convert.js"
]);
"use strict";
$import.map(
	"InvalidOperationException",
	[
  "scripts/joopl-toolbox/InvalidOperationException.js"
]);
"use strict";
$import.map(
	"Enumerable",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js"
]);
"use strict";
$import.map(
	"Enumerator",
	[
  "scripts/joopl-toolbox/collections/Enumerator.js"
]);
"use strict";
$import.map(
	"Index",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/Index.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queue.js"
]);
"use strict";
$import.map(
	"IndexedList",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableList.js",
  "scripts/joopl-toolbox/collections/IndexedList.js",
  "scripts/joopl-toolbox/collections/Index.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/Queryable.js"
]);
"use strict";
$import.map(
	"joopl.collections",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableList.js",
  "scripts/joopl-toolbox/collections/IndexedList.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/Index.js",
  "scripts/joopl-toolbox/collections/OrderedStringIndex.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/A.js",
  "scripts/joopl-toolbox/B.js",
  "scripts/joopl-toolbox/InvalidOperationException.js"
]);
"use strict";
$import.map(
	"List",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/Queue.js"
]);
"use strict";
$import.map(
	"ListEnumerator",
	[
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js"
]);
"use strict";
$import.map(
	"ObservableChange",
	[
  "scripts/joopl-toolbox/collections/ObservableChange.js"
]);
"use strict";
$import.map(
	"ObservableList",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableList.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/Queryable.js"
]);
"use strict";
$import.map(
	"OrderedStringIndex",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/Index.js",
  "scripts/joopl-toolbox/collections/OrderedStringIndex.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/ObservableChange.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queue.js"
]);
"use strict";
$import.map(
	"Queryable",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/List.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js"
]);
"use strict";
$import.map(
	"Queue",
	[
  "scripts/joopl-toolbox/collections/Enumerable.js",
  "scripts/joopl-toolbox/collections/Queue.js",
  "scripts/joopl-toolbox/collections/Enumerator.js",
  "scripts/joopl-toolbox/collections/ListEnumerator.js",
  "scripts/joopl-toolbox/collections/Queryable.js",
  "scripts/joopl-toolbox/InvalidOperationException.js",
  "scripts/joopl-toolbox/collections/List.js"
]);
